/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AiOperationsIndexRouteImport } from './routes/ai-operations.index'
import { Route as AiOperationsHistoryRouteImport } from './routes/ai-operations.history'
import { Route as AiOperationsExceptionsExceptionIdRouteImport } from './routes/ai-operations.exceptions.$exceptionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AiOperationsIndexRoute = AiOperationsIndexRouteImport.update({
  id: '/ai-operations/',
  path: '/ai-operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiOperationsHistoryRoute = AiOperationsHistoryRouteImport.update({
  id: '/ai-operations/history',
  path: '/ai-operations/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AiOperationsExceptionsExceptionIdRoute =
  AiOperationsExceptionsExceptionIdRouteImport.update({
    id: '/ai-operations/exceptions/$exceptionId',
    path: '/ai-operations/exceptions/$exceptionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/logistics': typeof LogisticsRoute
  '/orders': typeof OrdersRoute
  '/production': typeof ProductionRoute
  '/upload': typeof UploadRoute
  '/ai-operations/history': typeof AiOperationsHistoryRoute
  '/ai-operations/': typeof AiOperationsIndexRoute
  '/ai-operations/exceptions/$exceptionId': typeof AiOperationsExceptionsExceptionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/logistics': typeof LogisticsRoute
  '/orders': typeof OrdersRoute
  '/production': typeof ProductionRoute
  '/upload': typeof UploadRoute
  '/ai-operations/history': typeof AiOperationsHistoryRoute
  '/ai-operations': typeof AiOperationsIndexRoute
  '/ai-operations/exceptions/$exceptionId': typeof AiOperationsExceptionsExceptionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/logistics': typeof LogisticsRoute
  '/orders': typeof OrdersRoute
  '/production': typeof ProductionRoute
  '/upload': typeof UploadRoute
  '/ai-operations/history': typeof AiOperationsHistoryRoute
  '/ai-operations/': typeof AiOperationsIndexRoute
  '/ai-operations/exceptions/$exceptionId': typeof AiOperationsExceptionsExceptionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/inventory'
    | '/logistics'
    | '/orders'
    | '/production'
    | '/upload'
    | '/ai-operations/history'
    | '/ai-operations/'
    | '/ai-operations/exceptions/$exceptionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance'
    | '/inventory'
    | '/logistics'
    | '/orders'
    | '/production'
    | '/upload'
    | '/ai-operations/history'
    | '/ai-operations'
    | '/ai-operations/exceptions/$exceptionId'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/inventory'
    | '/logistics'
    | '/orders'
    | '/production'
    | '/upload'
    | '/ai-operations/history'
    | '/ai-operations/'
    | '/ai-operations/exceptions/$exceptionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRoute
  InventoryRoute: typeof InventoryRoute
  LogisticsRoute: typeof LogisticsRoute
  OrdersRoute: typeof OrdersRoute
  ProductionRoute: typeof ProductionRoute
  UploadRoute: typeof UploadRoute
  AiOperationsHistoryRoute: typeof AiOperationsHistoryRoute
  AiOperationsIndexRoute: typeof AiOperationsIndexRoute
  AiOperationsExceptionsExceptionIdRoute: typeof AiOperationsExceptionsExceptionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-operations/': {
      id: '/ai-operations/'
      path: '/ai-operations'
      fullPath: '/ai-operations/'
      preLoaderRoute: typeof AiOperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-operations/history': {
      id: '/ai-operations/history'
      path: '/ai-operations/history'
      fullPath: '/ai-operations/history'
      preLoaderRoute: typeof AiOperationsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-operations/exceptions/$exceptionId': {
      id: '/ai-operations/exceptions/$exceptionId'
      path: '/ai-operations/exceptions/$exceptionId'
      fullPath: '/ai-operations/exceptions/$exceptionId'
      preLoaderRoute: typeof AiOperationsExceptionsExceptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRoute,
  InventoryRoute: InventoryRoute,
  LogisticsRoute: LogisticsRoute,
  OrdersRoute: OrdersRoute,
  ProductionRoute: ProductionRoute,
  UploadRoute: UploadRoute,
  AiOperationsHistoryRoute: AiOperationsHistoryRoute,
  AiOperationsIndexRoute: AiOperationsIndexRoute,
  AiOperationsExceptionsExceptionIdRoute:
    AiOperationsExceptionsExceptionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
